# Generated by Django 6.1.1 on 2026-09-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('ano_publicacao', models.IntegerField()),
                ('quantidade_disponivel', models.IntegerField(default=0)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='livros',
        ),
    ]
