# Generated by Django 6.1.1 on 2026-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('data_retirada', models.DateField()),
                ('data_devolucao', models.DateField()),
            ],
        ),
    ]
