# Generated by Django 6.1.1 on 2026-09-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('data_retirada', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='emprestado', max_length=20)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='emprestimos',
        ),
    ]
