# Generated by Django 6.1.1 on 2026-09-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_emprestimo_delete_emprestimos'),
        ('livros', '0002_livro_delete_livros'),
        ('usuarios', '0002_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
