# Generated by Django 6.1.1 on 2026-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimo_livro_alter_emprestimo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
