# Generated by Django 6.1.1 on 2026-10-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_alter_emprestimo_livro_alter_emprestimo_usuario'),
        ('livros', '0002_livro_delete_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='livros.livro'),
        ),
    ]
